package com.SAPTOOL.ui.SmartHub.SmartGen;

import com.SAPTOOL.utils.Generic;
import com.SAPTOOL.utils.GlobalConstants;

import java.io.File;

/**
 *
 * @author bvatrapu
 */
public class SelectPage extends javax.swing.JFrame {

    /**
     * Creates new form SelectPage
     */
    public SelectPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        comboPages = new javax.swing.JComboBox<>();
        btnGo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SelectPage");

        comboPages.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnGo.setText("GO");
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(comboPages, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btnGo, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(comboPages)
                        .addComponent(btnGo, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
        setVisible(true);
    }
    public static void initLoad(){
        comboPages.removeAllItems();
        String[] allPages=null;
        String page=null;
        allPages = Generic.getAllFileNames(GlobalConstants.SELECTED_PROJECT_PATH+ File.separator+GlobalConstants.TEST_FRAMEWORK_TESTPAGES_FOLDER+"/");
        for(int i=0;i<=allPages.length-1;i++){
            if(allPages[i].contains(".java")){
                page=allPages[i].replaceAll(".java","");
            }
            comboPages.addItem(page);
        }
    }
    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {
        GlobalConstants.TestScript_Selected_Page_Name=comboPages.getSelectedItem().toString();

        switch (GlobalConstants.TestScript_Button_Name.toUpperCase()){
            case "OBJECT":
                PageObjects pageObjects=new PageObjects();
                pageObjects.setVisible(true);
                pageObjects.initLoad();
                break;
            case "OPERATION":
                PageOperations pageOperations=new PageOperations();
                pageOperations.setVisible(true);
                pageOperations.initLoad();
                break;
            case "METHOD":
                PageMethods pageMethods = new PageMethods();
                pageMethods.setVisible(true);
                pageMethods.initLoad();
                break;

        }
        dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnGo;
    public static javax.swing.JComboBox<String> comboPages;
    // End of variables decl
    // aration
}
